language: java
jdk: openjdk11

os:
  - linux

env:
  global:
    - API_FOLDER="api/java/pokedex-api/"
    - JARNAME="pokeapi.jar"
    - ARTEFACT="pokedex-api-1.0-runner.jar"
    - PACKAGE="pokeapi.java.tar.gz"

script:
  - cd $API_FOLDER
  - ./mvnw package
  -  #mkdir dir
  -  #cp target/$ARTEFACT dir/$JARNAME
  -  #tar cvzf $PACKAGE dir/