language: java
jdk: openjdk11

os:
  - linux

env:
  global:
    - API_FOLDER="api/java/pokedex-api/" 
    - JARNAME="pokeapi.jar" 
    - ARTEFACT="pokedex-api-1.0-runner.jar" 
    - HOST="151.80.57.175" 
    - LOGIN="root" 
    - PASS="Fcyvk1Mi" 
    - PACKAGE="pokeapi.java.tar.gz"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install sshpass

script:
  - cd $API_FOLDER
  - ./mvnw package
  - mkdir package
  - cp target/$ARTEFACT package/$JARNAME
  - tar cvzf $PACKAGE package/
  - sshpass -p $PASS scp $PACKAGE root@$HOST:~/deploy/