language: java
jdk: openjdk11

os:
  - linux

env:
  global:
    - API_FOLDER="api/java/pokedex-api/" 
    - JARNAME="pokeapi.jar" 
    - ARTEFACT="pokedex-api-1.0-runner.jar" 
    - FTPIP="151.80.57.175" 
    - FTPPORT="8800" 
    - FTPLOGIN="yao" 
    - FTPPASS="kawai" 
    - PACKAGE="pokeapi.java.tar.gz"
 
script:
  - cp ftp.sh $API_FOLDER/.
  - cd $API_FOLDER
  - ./mvnw package
  - mkdir package
  - cp target/$ARTEFACT package/$JARNAME
  - tar cvzf $PACKAGE package/
  - chmod u+x ftp.sh
  - ./ftp.sh